using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection.Emit;
using Assets.Scripts;
using Assets.Scripts.Inventory;
using Assets.Scripts.Objects.Items;
using HarmonyLib;

namespace ExampleMod
{
    // Example patch: skip breathing
    [HarmonyPatch(typeof(Lungs), nameof(Lungs.TakeBreath))]
    public static class Patch_Lungs_TakeBreath
    {
        // A prefix function can either return void (run the prefix before the original),
        // or a bool, saying whether to run the original method (true) or skip it (false).
        [HarmonyPrefix]
        public static bool Prefix()
        {
            // Skip the original TakeBreath method, effectively disabling breathing
            return false;
        }
    }

    // Example patch: print the time spent to find new rooms in the game, but only if it took longer than 10 ms
    [HarmonyPatch(typeof(RoomController), nameof(RoomController.ThreadedWork))]
    public static class Patch_RoomController_ThreadedWork
    {
        private static Stopwatch stopwatch = new Stopwatch();

        [HarmonyPrefix]
        public static void Prefix()
        {
            // start the stopwatch before the original method is called
            stopwatch.Restart();
        }

        [HarmonyPostfix]
        public static void Postfix()
        {
            // stop the stopwatch after the original method finished
            stopwatch.Stop();
            var elapsed = stopwatch.ElapsedMilliseconds;
            if (elapsed >= 10) // Only log if it took more than 10 ms
            {
                UnityEngine.Debug.Log(
                    $"[ExampleMod] RoomController.ThreadedWork took {stopwatch.ElapsedMilliseconds} ms"
                );
            }
        }
    }

    // Example patch to change the blueprint color to blue instead of yellow,
    // when cable/pipe ports are matching
    // This is done via a transpiler, which modifies the actual IL code of the method.
    //
    // The code below was generated by AI giving it the original ("decompiled") method code as input,
    // and asking it to replace Color.yellow with Color.blue.
    [HarmonyPatch(typeof(InventoryManager), nameof(InventoryManager.PlacementMode))]
    public static class Patch_InventoryManager_PlacementMode
    {
        [HarmonyTranspiler]
        public static IEnumerable<CodeInstruction> Transpiler(
            IEnumerable<CodeInstruction> instructions
        )
        {
            var code = new List<CodeInstruction>(instructions);

            // Getters for Color.yellow and Color.blue
            var colorYellowGetter = AccessTools.PropertyGetter(
                typeof(UnityEngine.Color),
                nameof(UnityEngine.Color.yellow)
            );
            var colorBlueGetter = AccessTools.PropertyGetter(
                typeof(UnityEngine.Color),
                nameof(UnityEngine.Color.blue)
            );

            for (int i = 0; i < code.Count; i++)
            {
                // Replace any call to Color.yellow with Color.blue
                if (code[i].Calls(colorYellowGetter))
                {
                    code[i] = new CodeInstruction(OpCodes.Call, colorBlueGetter)
                        .WithLabels(code[i].labels) // Preserve labels, if any
                        .WithBlocks(code[i].blocks); // Preserve exception blocks, if any
                }
            }
            return code;
        }
    }
}
