using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection.Emit;
using Assets.Scripts;
using Assets.Scripts.Inventory;
using Assets.Scripts.Objects.Items;
using HarmonyLib;

namespace ExampleMod;

// Example patch: skip breathing entirely
[HarmonyPatch(typeof(Lungs), nameof(Lungs.TakeBreath))]
public static class Patch_Lungs_TakeBreath
{
    // A prefix can return:
    // - void  -> always run the original
    // - bool  -> true  = run original, false = skip original
    [HarmonyPrefix]
    public static bool Prefix()
    {
        return true;
    }
}

// Example patch: log time spent finding new rooms, but only if it took longer than 10 ms
[HarmonyPatch(typeof(RoomController), nameof(RoomController.ThreadedWork))]
public static class Patch_RoomController_ThreadedWork
{
    private static readonly Stopwatch _stopwatch = new();

    [HarmonyPrefix]
    public static void Prefix()
    {
        // Start the stopwatch before the original method is called
        _stopwatch.Restart();
    }

    [HarmonyPostfix]
    public static void Postfix()
    {
        // Stop the stopwatch after the original method finished
        _stopwatch.Stop();

        var elapsed = _stopwatch.ElapsedMilliseconds;
        if (elapsed >= 10) // Only log if it took more than 10 ms
        {
            UnityEngine.Debug.Log($"[{ThisAssembly.AssemblyName}] RoomController.ThreadedWork took {elapsed} ms");
        }
    }
}

// Example patch to change the blueprint color to blue instead of yellow
// when cable/pipe ports are matching.
// This is done via a transpiler, which modifies the IL of the method.
//
// The code below was originally generated by AI given the "decompiled" method code
// and asked to replace Color.yellow with Color.blue.
[HarmonyPatch(typeof(InventoryManager), nameof(InventoryManager.PlacementMode))]
public static class Patch_InventoryManager_PlacementMode
{
    [HarmonyTranspiler]
    public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
    {
        var code = new List<CodeInstruction>(instructions);

        // Getters for Color.yellow and Color.blue
        var colorYellowGetter = AccessTools.PropertyGetter(
            typeof(UnityEngine.Color),
            nameof(UnityEngine.Color.yellow)
        );
        var colorBlueGetter = AccessTools.PropertyGetter(
            typeof(UnityEngine.Color),
            nameof(UnityEngine.Color.blue)
        );

        for (var i = 0; i < code.Count; i++)
        {
            // Replace any call to Color.yellow with Color.blue
            if (!code[i].Calls(colorYellowGetter))
            {
                continue;
            }

            code[i] = new CodeInstruction(OpCodes.Call, colorBlueGetter)
                .WithLabels(code[i].labels) // Preserve labels, if any
                .WithBlocks(code[i].blocks); // Preserve exception blocks, if any
        }

        return code;
    }
}
